version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    commit_message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
